version: 2

builds:
  - id: provider
    main: ./cmd/terraform-provider-elbv2
    env: [ CGO_ENABLED=0 ]
    goos: [ linux, darwin ]
    goarch: [ amd64, arm64 ]

release:
  prerelease: auto
  github:
    owner: skpr
    name: terraform-provider-elbv2
